# Card Encryption
card:
  cipher:
    algorithm: DESede
    secret-key: kakaopaykakaopaykakaopay
    separator: _
spring:
  # H2 DB Info
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    driver-class-name: org.h2.Driver
    username: sa
  #JPA Setting
  jpa:
    show-sql: true
    hibernate:
#      ddl-auto: create
      hibernate.hbm2ddl.auto: update
  redis:
    port: 6379
    host: localhost